services:
  rag-server:
    build: .
    image: server-rag
    container_name: server-rag
    ports:
      - "3500:3500"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
